### ISSUE TITLE
Issue with employees.get_all()

### ISSUE THREAD

**Issue by DClabaut** [fylein/netsuite-sdk-py#132]
Hello,

I'm new to Netsuitesdk, I am trying to get a list of all my employees.

I can login OK, and make simple queries like this one:

```
>>> nc.employees.count()
145
```

I can also query `nc.employees.get(UID)` successfully.

However, this query fails, and it looks like the issue is with the module itself not permissions:

```
>>> nc.employees.get_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/netsuitesdk/api/base.py", line 36, in get_all
    generated_records = self.get_all_generator()
  File "/home/user/.local/lib/python3.10/site-packages/netsuitesdk/api/employees.py", line 24, in get_all_generator
    if last_modified_date_query['search_value'] and last_modified_date_query['operator']:
TypeError: 'set' object is not subscriptable
```

Please advise

Thank you

**Comment by Hrishabh17** [comment]
@DClabaut we have released a patch for this issue, you can check out the [master branch](https://github.com/fylein/netsuite-sdk-py) or install latest version of [netsuitesdk](https://pypi.org/project/netsuitesdk/) i.e. `2.21.4`. Closing the issue, please re-open if the need be.
