### ISSUE TITLE
Issue with get Project (Job)

### ISSUE THREAD

**Issue by arplei** [fylein/netsuite-sdk-py#134]
Not all fields are included in the response for "Get Project" (project_response = nc.projects.get(internalId)). 
Missing is:

billingRateCard
createChargeRule
calculatedStartDate
plannedWork
plannedWorkBaseline
projectManager
scheduledEndDate
schedulingMethod
sourceServiceItemFromRateCard
timeApproval

https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2023_2/schema/record/job.html

Is this a problem with the SDK or possibly with our Netsuite instance?

**Comment by Hrishabh17** [comment]
@arplei The Project schema shared is from the wsdl version `2023_2`, in current implementation the default wsdl version is `2019_1`, if you wish to use the `v2023_2`, we have added support for that.
Please check out the [master branch](https://github.com/fylein/netsuite-sdk-py) or install latest version of [netsuitesdk](https://pypi.org/project/netsuitesdk/) i.e. `2.22.0`

While initializing the NetsuiteConnection, pass an additional param, wsdl_version with value `'2023_2'` as follows:

```
def connect_tba():
    NS_ACCOUNT = os.getenv('NS_ACCOUNT')
    NS_CONSUMER_KEY = os.getenv('NS_CONSUMER_KEY')
    NS_CONSUMER_SECRET = os.getenv('NS_CONSUMER_SECRET')
    NS_TOKEN_KEY = os.getenv('NS_TOKEN_KEY')
    NS_TOKEN_SECRET = os.getenv('NS_TOKEN_SECRET')
    nc = NetSuiteConnection(
        account=NS_ACCOUNT,
        consumer_key=NS_CONSUMER_KEY,
        consumer_secret=NS_CONSUMER_SECRET,
        token_key=NS_TOKEN_KEY,
        token_secret=NS_TOKEN_SECRET,
        wsdl_version='2023_2'   #optional param to use wsdl version other than '2019_1' 
    )
```
The following details have been added in the readme, please to check out that as well. Closing the issue, please re-open if the need be.
