### ISSUE TITLE
ImportError: cannot import name 'NetSuiteClient' from 'netsuitesdk' 

### ISSUE THREAD

**Issue by yingmu52** [fylein/netsuite-sdk-py#21]
I am getting import error 
```
Traceback (most recent call last):
  File "/Users/xinyi/projects/netsuite/py/src/try1.py", line 3, in <module>
    from netsuitesdk import NetSuiteClient, PaginatedSearch
ImportError: cannot import name 'NetSuiteClient' from 'netsuitesdk' (/Users/xinyi/projects/netsuite/py/venv/lib/python3.7/site-packages/netsuitesdk/__init__.py)
```

any help would be awesome!

**Comment by snarayanank2** [comment]
@yingmu52 NetSuiteClient is an internal class that is not meant to be used directly. Please use NetSuiteConnection class (you can check the README) - it has much simpler interfaces. HTH.

**Comment by yingmu52** [comment]
@snarayanank2 HI, I was following this example, 
https://github.com/fylein/netsuite-sdk-py/blob/master/examples/search_all.py

it imports these
`from netsuitesdk import NetSuiteClient, PaginatedSearch`

what do you suggest to implement search all with pagination with `NetSuiteConnection` ?

**Comment by snarayanank2** [comment]
Ah, the examples are outdated. Will remove them - thanks for pointing it out.

Search all is already implemented with pagination for some types. The base class is here https://github.com/fylein/netsuite-sdk-py/blob/master/netsuitesdk/api/base.py 

Can you tell me a little more about what you're looking to achieve? Maybe I can advise on the best way to go about it.

**Comment by yingmu52** [comment]
@snarayanank2 awesome, thank for you for looking into this, I have been trying to use this SDK to pull data from NetSuite. 

The data that I am particularly interested in are listed as following 
- Lists
    - Transactions
        - Purchases
        - Sales
        - Customers 
- Reports
    - Purchases
    - Inventory/items
    - Sales
    - Sales order

However, I was confused that out of the box if only gives me the following data
- Accounts
- classifications
- departments
- locations
- currencies
- vendors
- vendor_bills
and If I understand it correctly, the data that I intended to pull can only be done through search functions. 

If you could advise me on some examples with this SDK to pull the data that I am interested in, that will very helpful. 

Thank you

**Comment by snarayanank2** [comment]
That was helpful. Thanks.

So we don't have support for these types out of the box. However, it should be relatively easy to add them to the SDK. It will be great if you can contribute it back. 

E.g. vendor_bills Is actually a kind of a Transaction. See https://github.com/fylein/netsuite-sdk-py/blob/master/netsuitesdk/api/vendor_bills.py

The goal of the SDK is to abstract out the SOAP stuff from the clients who should just speak simpler structures. All the SOAP stuff is inside the internal folder. You'll probably need to modify 
 https://github.com/fylein/netsuite-sdk-py/blob/master/netsuitesdk/internal/netsuite_types.py 

HTH

**Comment by pvahabi** [comment]
@yingmu52 were you able to extract with this library the item inventory ? I don't understand how to use the search for the inventory level. 

Let me know it would be very helpful to have an example of search all to extract that.

**Comment by pvahabi** [comment]
@snarayanank2 it would be great to have a couple of more examples: 
- search all without selecting a particular object type, or in general end to end search example 

What I'm interested in is given the internalId ID to extract the price and inventory.
