### ISSUE TITLE
Invalid login attempt.

### ISSUE THREAD

**Issue by Shubham-S-Yadav** [fylein/netsuite-sdk-py#29]
Hi,

I tried executing the example you shared with my account credential but it is giving me following error:
**zeep.exceptions.Fault: Invalid login attempt.**

**Comment by Shwetabhk** [comment]
Hi Shubham, would recommend trying to generate credentials in the manner once
https://www.fylehq.com/help/en/articles/2012953-integration-with-oracle-netsuite

**Comment by wolever** [comment]
This can also happen for sandbox domains if the `sb` is lowercase instead of upper case: `12345_SB1` is correct, but `12345_sb1` will cause an "invalid login attempt"
