### ISSUE TITLE
Saved search support

### ISSUE THREAD

**Issue by Code-nomad** [fylein/netsuite-sdk-py#38]
Hi, 

First off thanks for taking the time to put this together. It really helps to cut through the netsuite jungle of data.

Second, is there support for getting saved searches from netsuite? 

kind regards,

Lucas

**Comment by gustahrodrigues** [comment]
I've added support for running a saved search on [PR 60](https://github.com/fylein/netsuite-sdk-py/pull/60)

**Comment by renjithpaul27** [comment]
When can we expect this PR to merge ? It is open for quite sometime.
