### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by Techloyce-Odoo** [fylein/netsuite-sdk-py#40]
Hi, I'm using this sdk to get data from my NetSuite I've my credentials which are working in Postman but unable to use this sdk.

`NetSuiteConnection(
            account=NS_ACCOUNT,
            consumer_key=NS_CONSUMER_KEY,
            consumer_secret=NS_CONSUMER_SECRET,
            token_key=NS_TOKEN_KEY,
            token_secret=NS_TOKEN_SECRET
        )`

This code me giving me an error any help would be appreciated.

**Comment by Shwetabhk** [comment]
The SDK uses SQLite for caching, is it possible that the environment you're running it in doesn't support SQLite?

**Comment by falz** [comment]
Testing this for the first time as well, code is only attempting to make a connection just like the original post. Here's the error, I suspect Techloyce-Odoo got the same error?

```
Traceback (most recent call last):
  File "./netsuite-sdktest.py", line 25, in <module>
    token_secret =      token_secret
  File "/usr/local/lib/python3.6/site-packages/netsuitesdk/connection.py", line 27, in __init__
    page_size=page_size)
  File "/usr/local/lib/python3.6/site-packages/netsuitesdk/internal/client.py", line 66, in __init__
    cache = SqliteCache(path=path, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/zeep/cache.py", line 121, in __init__
    with self.db_connection() as conn:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/zeep/cache.py", line 135, in db_connection
    self._db_path, detect_types=sqlite3.PARSE_DECLTYPES
sqlite3.OperationalError: unable to open database file
```

**Comment by falz** [comment]
Found the issue, but unsure the proper fix. this uses zeep.cache. inside **netsuitesdk/internal/client.py** we have:

``` 
       if caching:
            path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'cache.db')
            timeout = caching_timeout
            cache = SqliteCache(path=path, timeout=timeout)
            transport = Transport(cache=cache)
```

On my system (Centos 7) it's writing this file to **/usr/local/lib/python3.6/site-packages/netsuitesdk/internal/cache.db** which is clearly wrong.

For testing and for my purposes, ive made this change to **client.py** as a workaround for now:
```
        if caching:
            #path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'cache.db')
            path = '/tmp/cache.db' 
```

**Comment by ashwin1111** [comment]
Hey @falz,
We have exposed caching settings (https://github.com/fylein/netsuite-sdk-py/pull/48/files) You will be able to enable or disable caching and also modify the cache path. Closing this issue, please reopen if the issue persists, thanks.
