### ISSUE TITLE
[Request] Delete invoice

### ISSUE THREAD

**Issue by bentlusty** [fylein/netsuite-sdk-py#54]
Hey all, great project!

Is there a way to delete an invoice with the sdk?

thanks,
B.

**Comment by VeNoMouS** [comment]
From what I can see ... it doesn't have a full CRUD function set... so you would need to do it manually i via `ns.client.request`

I am a complete noob with netsuite im learning as I go.. the lack of real world examples is the biggest hurdle that i am finding...

**Comment by VeNoMouS** [comment]
@bentlusty dunno if this is required... but i did find this...

https://netsuiteprofessionals.com/question/deleting-records-and-recording-the-reason-memo-ss1-0-ss2-0/

**Comment by bentlusty** [comment]
Yeah, I used the `request` here

**Comment by samadsajanlal** [comment]
@bentlusty are you able to provide a sample request for deleting something? I'm trying to delete a file using ns.client.request and haven't had much luck.
