### ISSUE TITLE
[Question] Can you access data for a certain report?

### ISSUE THREAD

**Issue by jadenmazzone** [fylein/netsuite-sdk-py#75]
Is it possible to access data for a certain report, or does this SDK not do that? If it doesn't, then any suggestions on how to do that?

**Comment by Sravanksk** [comment]
Hi @jadenmazzone, Yes it is possible to access data of a certain report using its internal ID. 

Here is a sample code snippet
```
    from netsuitesdk import NetSuiteConnection

    netsuite_connection = NetSuiteConnection(
       account=NS_ACCOUNT,
       consumer_key=NS_CONSUMER_KEY,
       consumer_secret=NS_CONSUMER_SECRET,
       token_key=NS_TOKEN_KEY,
       token_secret=NS_TOKEN_SECRET
    )

    data = netsuite_connection.expense_reports.get(internalId=252297)
    print(data)

**Comment by KenleyGrantCardone** [comment]
Hello @Sravanksk I got this error?

netsuitesdk.internal.exceptions.NetSuiteRequestError: code: UNEXPECTED_ERROR, message: An error occured in a get request: An unexpected error occurred. Error ID: lrgwe31f19g4sdwikbg1w

**Comment by thegoose32** [comment]
Hi @Sravanksk - in the example above, you are requesting an expense report. How would you request a custom trial balance report?
