### ISSUE TITLE
[Help] Attaching files with Vendor record

### ISSUE THREAD

**Issue by iamhssingh** [fylein/netsuite-sdk-py#85]
I can create `Folders` and `Files`. How can I attach `Files` with `Vendors`?

I googled through a few NetSuite doc, tried `AttachBasicReference` and other multiple things. But I cannot figure this one out.

**Comment by RuudvdBoomen** [comment]
I'm facing the same problem! Did you find a solution already :)?

**Comment by iamhssingh** [comment]
Yeah, I found the solution @RuudvdBoomen

**Comment by iamhssingh** [comment]
1. Create a `folder` (Use: `Folder`)
2. Create a `file` in specific `Folder` (Use `File`)
3. Assuming that you've a `Vendor` record's `internalId`, the final step is to `attach` `file` to `vendor` record.

Here's the code for that:

```
ns_client: NetSuiteClient
attach_basic_ref = ns_client.AttachBasicReference()
attach_basic_ref.attachTo = ns_client.RecordRef(**{"internalId": vendor.internalId, "type": "vendor"})
attach_basic_ref.attachedRecord = ns_client.RecordRef(**{"internalId": file.internalId, "type": "file"})

# Finally, post to netsuite
ns_cllient.request("attach", attach_basic_ref)
```

**Comment by RuudvdBoomen** [comment]
@iamhssingh Thanks a lot for your answer! I tried it but, i encountered `'NetSuiteClient' object has no attribute 'AttachBasicReference'` this error. Do you have any idea what I'm doing wrong :thinking: ?

**Comment by iamhssingh** [comment]
@RuudvdBoomen Yes. You need to sort of monkey patch `AttachBasicReference` in `COMPLEX_TYPES`. Do this before you initialise `ns_client`:

`COMPLEX_TYPES["ns0"].append("AttachBasicReference")`

**Comment by RuudvdBoomen** [comment]
It works, thanks a lot! Your are our hero :smile:
