### ISSUE TITLE
Billing Account is not available for fetch

### ISSUE THREAD

**Issue by bazarnov** [fylein/netsuite-sdk-py#93]
Hello, faced with next issue:

```
search_cls = self.get_complex_type(search_cls_name)\n  File \"/Users/baz/gl/airbyte/airbyte-integrations/connectors/source
netsuite/.venv/lib/python3.9/site-packages/netsuitesdk/internal/client.py\", line 140, in get_complex_type\n    return
**self._complex_types[type_name]\nKeyError: 'BillingAccountSearch'\n", "failure_type": "system_error"}}}**
```
A little research shows that there is no object inside of `self._complex_types` called `BillingAccountSearch` only `BillingAccount` is available:
```
"ConsolidatedExchangeRateSearchBasic": <zeep.xsd.dynamic_types.ConsolidatedExchangeRateSearchBasic object at 0x7fba288b44c0>,
"ItemCostEstimateType": <zeep.xsd.dynamic_types.ItemCostEstimateType object at 0x7fba2785c250>,
"BillingAccount": <zeep.xsd.dynamic_types.BillingAccount object at 0x7fba27d7b190>,
"CustomerAddressbook": <zeep.xsd.dynamic_types.CustomerAddressbook object at 0x7fba27cbd880>,
"CustomerAddressbookList": <zeep.xsd.dynamic_types.CustomerAddressbookList object at 0x7fba27cbddc0>,
```

Is this something on my side, or generally issued as missing?

**Comment by bazarnov** [comment]
@RodrigoATorres tagging you as the latest person who committed here. Would appreciate any advice or explanation if such. Thanks!

**Comment by bazarnov** [comment]
@gustahrodrigues

**Comment by bazarnov** [comment]
@Sravanksk

**Comment by Sravanksk** [comment]
@bazarnov by looking at this error, I'm assuming that your basic search on BillingAccounts is failing.
```A little research shows that there is no object inside of self._complex_types called BillingAccountSearch only BillingAccount is available:```

To make the search work on BillingAccount, You'll have to add `'BillingAccountSearchBasic'` in **ns5** **COMPLEX_TYPE** in netsuite_types.py to make the search work.

Once `BillingAccountSearchBasic` is added in NetSuite complex types, your search would work as expected 
```
search_object = netsuite_connection.billing_accounts.search(attribute='id', value='1', operator='is'))
print(search_object)
```

Thanks

**Comment by bazarnov** [comment]
I'll try, will keep you posted.

**Comment by Sravanksk** [comment]
@bazarnov I have fixed the issue for now. Please check this [commit](https://github.com/fylein/netsuite-sdk-py/commit/35b6d9ae8eb937f7e2c7d224ed5ea05e34f22f7b) for more info.
Please test this by installing the latest version -> `netsuitesdk==2.14.0`

Thanks

**Comment by bazarnov** [comment]
Works perfectly, thank you! Could you also take a look at this issue, I need a complete picture on search as well: https://github.com/fylein/netsuite-sdk-py/issues/71#issuecomment-1243692750

The attention to this is much appreciated.
